Repository Caleydo/tdp_publicdb, pull requests merged in 2020-03, with the labels that each got.

#63 Add additional cell line scores HLA Type, MSI, ...
  src/config.ts
  tdp_publicdb/entity.py
Labels: release: minor, type: feature

#76 Update to Typescript 3.8
  package.json
  tsconfig.json
Labels: priority: high, release: major, type: refactor

#86 Update dependencies and requirements
  package.json
  requirements.txt
  requirements_dev.txt
  tdp_publicdb/query_gene.py
  tdp_publicdb/query_score.py
Labels: dependencies, priority: medium, type: refactor

#88 Change `buildId` to `JSON.stringify(buildId)`
  webpack.config.js
Labels: priority: medium, type: refactor

#89 Release 7.0.0
  .github/CODEOWNERS
  package.json
  requirements.txt
  requirements_dev.txt
  src/config.ts
  tdp_publicdb/entity.py
  tdp_publicdb/query_gene.py
  tdp_publicdb/query_score.py
  tsconfig.json
  webpack.config.js
Labels: release: major

#84 Update docker image to postgress12.1
  deploy/docker-compose.partial.yml
Labels: release: major, type: technical debt

#85 Add pgAdmin container docker-compose-debug.partial.yml
  deploy/docker-compose-debug.partial.yml
Labels: release: minor, type: feature

#93 Make repository public
  package.json
Labels: release: major, type: refactor

#74 Migrate to jest for testing
  jest.config.js
  karma.conf.js
  package.json
  src/IDTypeDetector.ts
  tox.ini
  tsd.d.ts
  tslint.json
  webpack.config.js
Labels: release: major, type: refactor
