Repository Caleydo/tdp_publicdb, pull requests merged in 2020-08, with the labels that each got.

#114 Release 8.0.1
  package.json
  phovea_registry.js
  requirements.txt
Labels: release: patch

#116 Fix drug screen score bug
  dist/scores/ScoreUtils.js
  dist/scores/ScoreUtils.js.map
  src/scores/ScoreUtils.ts
Labels: release: patch, type: bug

#117 Release 8.0.2
  .gitattributes
  README.md
  dist/scores/ScoreUtils.js
  dist/scores/ScoreUtils.js.map
  package.json
  src/scores/ScoreUtils.ts
Labels: release: patch

#118 Remove madge from dependencies
  package.json
Labels: dependencies
