Repository Caleydo/tdp_publicdb, pull requests merged in 2020-06, with the labels that each got.

#101 Add cellline Drug Screen score
  phovea.js
  src/config.ts
  src/forms.ts
  src/scores/ASingleScore.ts
  src/scores/SingleScore.ts
  src/scores/forms.ts
  src/scores/utils.ts
  src/styles/select2_overrides.scss
  src/utils.ts
  tdp_publicdb/__init__.py
  tdp_publicdb/data.py
  tdp_publicdb/entity.py
  tdp_publicdb/migration/env.py
  tdp_publicdb/migration/versions/20200603_0631_9ed460a9ea4a_add_drugscore_view.py
  tdp_publicdb/query_drug.py
  tdp_publicdb/sql.py
Labels: release: minor, type: feature

#102 Remove unknown category from score config
  src/config.ts
  src/scores/utils.ts
Labels: release: minor, type: refactor

#104 Set select2 and select3 placeholder explicitly
  src/forms.ts
  src/scores/SingleScore.ts
Labels: type: refactor

#106 Update LineUp v4 selectors in Ordino Welcome tour
  src/tours/index.ts
Labels: release: patch, type: bug
