Repository Caleydo/tdp_publicdb, pull requests merged in 2021-05, with the labels that each got.

#140 Modify column widths due to new bigger bootstrap 4 font size
  dist/common/config.js
  dist/common/config.js.map
  dist/scores/ABooleanScore.js
  dist/scores/GeneSignatureScore.js
  dist/scores/GeneSignatureScore.js.map
  src/common/config.ts
  src/scores/ABooleanScore.ts
  src/scores/GeneSignatureScore.ts
Labels: release: minor, type: refactor

#141 Replace `react-bootstrap` with plain Bootstrap
  dist/common/forms.d.ts
  dist/menu/DatasetCard.js
  dist/menu/DatasetCard.js.map
  dist/menu/DatasetSearchBox.js
  dist/menu/DatasetSearchBox.js.map
  src/menu/DatasetCard.tsx
  src/menu/DatasetSearchBox.tsx
Labels: type: refactor

#142 Remove old start menu and subsection extension point + add missing dependencies
  dist/common/forms.d.ts
  dist/menu/DatasetSearchBox.js.map
  dist/menu/index.d.ts
  dist/menu/index.js
  dist/menu/index.js.map
  dist/scores/AggregatedScore.d.ts
  dist/scores/forms.d.ts
  package.json
  src/menu/DatasetSearchBox.tsx
  src/menu/GeneSubSection.ts
  src/menu/SampleSubSection.ts
  src/menu/index.ts
Labels: type: refactor

#143 Store the correct species in the UserSession
  dist/menu/DatasetCard.js
  dist/menu/DatasetCard.js.map
  dist/menu/DatasetSearchBox.d.ts
  dist/menu/DatasetSearchBox.js
  dist/menu/DatasetSearchBox.js.map
  src/menu/DatasetCard.tsx
  src/menu/DatasetSearchBox.tsx
Labels: release: minor, type: bug

#144 Fix tours to match the new start menu and bootstrap 4 classes
  dist/base/extensions.d.ts
  dist/menu/DatasetCard.d.ts
  dist/menu/DatasetCard.js
  dist/menu/DatasetCard.js.map
  dist/menu/DatasetSearchBox.js
  dist/menu/DatasetSearchBox.js.map
  dist/phovea.js
  dist/phovea.js.map
  dist/tours/AddColumnToGeneListTour.js
  dist/tours/AddColumnToGeneListTour.js.map
  dist/tours/StartMenuTour.js
  dist/tours/StartMenuTour.js.map
  dist/tours/WelcomeTour.js
  dist/tours/WelcomeTour.js.map
  src/base/extensions.ts
  src/menu/DatasetCard.tsx
  src/menu/DatasetSearchBox.tsx
  src/phovea.ts
  src/tours/AddColumnToGeneListTour.ts
  src/tours/StartMenuTour.ts
  src/tours/WelcomeTour.ts
Labels: release: minor, type: refactor
