Repository Caleydo/tdp_publicdb, pull requests merged in 2022-06, with the labels that each got.

#188 Release 12.0.0
  .circleci/config.yml
  .gitignore
  .yo-rc.json
  MANIFEST.in
  Makefile
  buildPython.js
  dist/menu/DatasetCard.d.ts.map
  dist/menu/DatasetCard.js
  dist/menu/DatasetCard.js.map
  docs/.gitignore
  docs/_static/touch.txt
  docs/_templates/touch.txt
  docs/conf.py
  docs/index.rst
  package.json
  requirements.txt
  requirements_dev.txt
  setup.cfg
  setup.py
  src/menu/DatasetCard.tsx
  tdp_publicdb/__init__.py
  tdp_publicdb/config.json
  tdp_publicdb/data.py
  tdp_publicdb/entity.py
  tdp_publicdb/migration/env.py
  tdp_publicdb/migration/versions/20200302_1312_b477004c3673_First_Revision.py
  tdp_publicdb/migration/versions/20200420_0912_4c6cb36e57e0_add_additional_tissue_columns.py
  tdp_publicdb/migration/versions/20200420_1044_dd7c97913940_add_additional_cellline_columns.py
  tdp_publicdb/migration/versions/20200603_0631_9ed460a9ea4a_add_drugscore_view.py
  tdp_publicdb/migration/versions/20200908_0609_e40e7676eb1c_add_gene_signature_views.py
  tdp_publicdb/migration/versions/20211118_1048_ec6a94da4809_add_scientificname_to_tdp_drug.py
  tdp_publicdb/pg_agg_score.py
  tdp_publicdb/query_common.py
  tdp_publicdb/query_drug.py
  tdp_publicdb/query_gene.py
  tdp_publicdb/query_sample.py
  tdp_publicdb/query_score.py
  tdp_publicdb/settings.py
  tdp_publicdb/sql.py
  tdp_publicdb/tests/__init__.py
  tdp_publicdb/tests/conftest.py
  tdp_publicdb/tests/test_main_app.py
  tox.ini
Labels: release: major

#189 Replace `gene_map_ensgs` API requests with native idtype mapping
  dist/scores/forms.d.ts
  dist/views/CoExpression.d.ts
  dist/views/CoExpression.d.ts.map
  dist/views/ViewUtils.d.ts
  dist/views/ViewUtils.d.ts.map
  dist/views/ViewUtils.js
  dist/views/ViewUtils.js.map
  src/views/ViewUtils.ts
  tdp_publicdb/query_gene.py
Labels: type: refactor, release: patch

#187 Add additional depletion screen scores
  dist/common/config.d.ts
  dist/common/config.d.ts.map
  dist/common/config.js
  dist/common/config.js.map
  dist/scores/AggregatedScore.js
  dist/scores/AggregatedScore.js.map
  dist/scores/SingleScore.js
  dist/scores/SingleScore.js.map
  dist/scores/forms.d.ts
  fakeUsers.db
  src/common/config.ts
  src/scores/AggregatedScore.ts
  src/scores/SingleScore.ts
  tdp_publicdb/data.py
  tdp_publicdb/migration/versions/20220614_1244_5a8dc3921597_new_depletion_scores.py
Labels: type: feature, release: minor
