Repository Caleydo/tdp_publicdb, pull requests merged in 2022-09, with the labels that each got.

#203 Add nowrap to button, add scrollbar to searchbox
  src/menu/DatasetSearchBox.tsx
Labels: type: bug, release: minor

#202 Show CoExpression messages / errors
  src/views/ACoExpression.ts
Labels: type: bug, release: minor

#206 Fix sorting of chromosomes due to new typings
  dist/common/config.d.ts.map
  dist/common/config.js
  dist/common/config.js.map
  dist/menu/DatasetCard.d.ts
  dist/menu/DatasetCard.d.ts.map
  dist/menu/DatasetSearchBox.d.ts.map
  dist/menu/DatasetSearchBox.js
  dist/menu/DatasetSearchBox.js.map
  dist/views/ACoExpression.js
  dist/views/ACoExpression.js.map
  src/common/config.ts
Labels: type: bug, release: patch

#205 Release 13.0.1
  dist/common/config.d.ts.map
  dist/common/config.js
  dist/common/config.js.map
  dist/menu/DatasetCard.d.ts
  dist/menu/DatasetCard.d.ts.map
  dist/menu/DatasetSearchBox.d.ts.map
  dist/menu/DatasetSearchBox.js
  dist/menu/DatasetSearchBox.js.map
  dist/views/ACoExpression.js
  dist/views/ACoExpression.js.map
  package.json
  requirements.txt
  src/common/config.ts
  src/menu/DatasetSearchBox.tsx
  src/views/ACoExpression.ts
Labels: release: patch
