Repository Caleydo/tdp_publicdb, pull requests merged in 2023-07, with the labels that each got.

#224 ci: add permission to build.yml
  .github/workflows/build.yml
  tdp_publicdb/tests/test_main_app.py
Labels: type: technical debt, release: patch

#223 fix: data mapping for boxplot column
  dist/scores/AAggregatedScore.d.ts.map
  dist/scores/AAggregatedScore.js
  dist/scores/AAggregatedScore.js.map
  src/scores/AAggregatedScore.ts
Labels: type: bug, release: patch

#222 fix: improvements to new tours
  dist/phovea.d.ts.map
  dist/phovea.js
  dist/phovea.js.map
  dist/tours/AssessBCCellLinesTour.d.ts.map
  dist/tours/AssessBCCellLinesTour.js
  dist/tours/AssessBCCellLinesTour.js.map
  dist/tours/DrugTargetDiscoveryTour.d.ts.map
  dist/tours/DrugTargetDiscoveryTour.js
  dist/tours/DrugTargetDiscoveryTour.js.map
  dist/tours/PredictionTP53Tour.d.ts.map
  dist/tours/PredictionTP53Tour.js
  dist/tours/PredictionTP53Tour.js.map
  dist/tours/PredictionTP53Tour2.js
  src/phovea.ts
  src/tours/AssessBCCellLinesTour.ts
  src/tours/DrugTargetDiscoveryTour.ts
  src/tours/PredictionTP53Tour.ts
  src/tours/PredictionTP53Tour2.ts
Labels: type: refactor
